# Generated by Django 3.0 on 2022-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key='id', serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
